CREATE DATABASE Projeto_Semiestruturados;

CREATE TABLE Instituicoes (
    
    CODIGO_DA_IES INTEGER PRIMARY KEY NOT NULL,
    NOME_DA_IES VARCHAR(255) NOT NULL,
    SIGLA VARCHAR(255) NOT NULL,
    CATEGORIA_DA_IES VARCHAR(255) NOT NULL,
    COMUNITARIA BOOLEAN NOT NULL,
    CONFESSIONAL BOOLEAN NOT NULL,
    FILANTROPICA BOOLEAN NOT NULL,
    ORGANIZACAO_ACADEMICA VARCHAR(255)NOT NULL,
    SITUACAO_IES VARCHAR(255) NOT NULL

);

CREATE TABLE Municipio (
    
    CODIGO_DA_IES VARCHAR(255) PRIMARY KEY,
    MUNICIPIO VARCHAR(255) NOT NULL,
    UF VARCHAR(255) NOT NULL

);

CREATE TABLE CATEGORIA_DA_IES(

	SIGLA_DA_IES VARCHAR(255) PRIMARY KEY,
	CATEGORIA_DA_IES VARCHAR(255) NOT NULL
);

CREATE TABLE ORGANIZACAO_ACADEMICA(

	ORGANIZACAO_ACADEMICA VARCHAR (255) PRIMARY KEY
);

DROP TABLE Instituicoes;
DROP TABLE Municipio;
DROP TABLE ORGANIZACAO_ACADEMICA;
DROP TABLE CATEGORIA_DA_IES;


