CREATE DATABASE PROJETO_SEMIESTRUTURADOS

CREATE TABLE ORGANIZACAO_ACADEMICA(

	ORGANIZACAO_ACADEMICA VARCHAR (255) PRIMARY KEY
);

CREATE TABLE CATEGORIA_DA_IES(

	SIGLA VARCHAR(255) PRIMARY KEY,
	NOME_CATEGORIA VARCHAR(255) NOT NULL
);

CREATE TABLE MUNICIPIO (
    
    CODIGO_MUNICIPIO_IBGE INTEGER PRIMARY KEY,
	MUNICIPIO VARCHAR(255) NOT NULL,
    UF VARCHAR(255) NOT NULL

);

CREATE TABLE Instituicoes (
    
    CODIGO_DA_IES INTEGER PRIMARY KEY,
    NOME_DA_IES VARCHAR(255) NOT NULL,
    COMUNITARIA BOOLEAN NOT NULL,
    CONFESSIONAL BOOLEAN NOT NULL,
    FILANTROPICA BOOLEAN NOT NULL,
    SITUACAO_IES VARCHAR(255) NOT NULL,
	SIGLA VARCHAR(255) NOT NULL,
	ORGANIZACAO_ACADEMICA VARCHAR(255)NOT NULL,
    CATEGORIA_DA_IES VARCHAR(255) NOT NULL,
	CODIGO_MUNICIPIO_IBGE INTEGER NOT NULL,
	FOREIGN KEY (ORGANIZACAO_ACADEMICA)REFERENCES ORGANIZACAO_ACADEMICA(ORGANIZACAO_ACADEMICA),
	FOREIGN KEY (SIGLA)REFERENCES CATEGORIA_DA_IES(SIGLA),
	FOREIGN KEY (CODIGO_MUNICIPIO_IBGE)REFERENCES MUNICIPIO(CODIGO_MUNICIPIO_IBGE),
	
);



DROP TABLE Instituicoes;
DROP TABLE Municipio;
DROP TABLE ORGANIZACAO_ACADEMICA;
DROP TABLE CATEGORIA_DA_IES;

SELECT*FROM Instituicoes