CREATE DATABASE Projeto_Semiestruturados;

CREATE TABLE Instituicoes (
    
    ID SERIAL PRIMARY KEY,
    CODIGO_DA_IES INTEGER NOT NULL,
    NOME_DA_IES VARCHAR(255) NOT NULL,
    SIGLA_DA_IES VARCHAR(50) NOT NULL,
    CATEGORIA_DA_IES VARCHAR(50) NOT NULL,
    COMUNITARIA BOOLEAN NOT NULL,
    CONFESSIONAL BOOLEAN NOT NULL,
    FILANTROPICA BOOLEAN NOT NULL,
    ORGANIZACAO_ACADEMICA VARCHAR(50) NOT NULL,
    CODIGO_MUNICIPIO_IBGE FLOAT NOT NULL,
    MUNICIPIO VARCHAR(100) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    SITUACAO_IES VARCHAR(50) NOT NULL,

);
